image: golang:1.15



stages:
  - build
  - test
  - deploy

before_script:
  - mkdir -p binaries

after_script:
  - ls -l binaries

# do not forget to set project variables
include:
  - template: SAST.gitlab-ci.yml # GITLAB_FEATURES = "sast"
  - template: License-Management.gitlab-ci.yml # GITLAB_FEATURES = "license_management"

variables:
  SAST_DISABLE_DIND: "true"
  SAST_GOSEC_LEVEL: 0



.dependency_command: &dependency_command
- go get github.com/joho/godotenv
- go get gitlab.com/rbrt-weiler/go-module-envordef
- go get gitlab.com/rbrt-weiler/go-module-xmcnbiclient

.build_command: &build_command
- go build -o binaries/GenericNbiClient GenericNbiClient.go

.build_command_release: &build_command_release
- GOOS=linux GOARCH=amd64 go build -o binaries/GenericNbiClient_${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}_linux64 GenericNbiClient.go
- GOOS=windows GOARCH=amd64 go build -o binaries/GenericNbiClient_${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}_win64.exe GenericNbiClient.go
- GOOS=darwin GOARCH=amd64 go build -o binaries/GenericNbiClient_${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}_darwin64 GenericNbiClient.go

.test_command: &test_command
- ./binaries/GenericNbiClient -version

.release_command: &release_command
- rm binaries/GenericNbiClient
- ln -s binaries GenericNbiClient_${CI_COMMIT_TAG}



build-dev:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
      allow_failure: true
  cache:
    key: "dev-$CI_COMMIT_SHA"
    paths:
      - binaries
  script:
    - *dependency_command
    - *build_command
  allow_failure: true

test-dev:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
      allow_failure: true
  cache:
    key: "dev-$CI_COMMIT_SHA"
    paths:
      - binaries
  script:
    - *test_command
  allow_failure: true



build-stable:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "stable"
      when: always
  cache:
    key: "staging-$CI_COMMIT_SHA"
    paths:
      - binaries
  script:
    - *dependency_command
    - *build_command

test-stable:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "stable"
      when: on_success
  cache:
    key: "staging-$CI_COMMIT_SHA"
    paths:
      - binaries
  script:
    - *test_command
  artifacts:
    when: on_success
    expire_in: 30 minutes
    name: "GenericNbiClient_${CI_COMMIT_SHORT_SHA}"
    paths:
      - binaries/*



build-tagged:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  cache:
    key: "release-$CI_COMMIT_SHA"
    paths:
      - binaries
  script:
    - *dependency_command
    - *build_command
    - *build_command_release

test-tagged:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  cache:
    key: "release-$CI_COMMIT_SHA"
    paths:
      - binaries
  script:
    - *test_command

deploy-tagged:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  cache:
    key: "release-$CI_COMMIT_SHA"
    paths:
      - binaries
  script:
    - *release_command
  artifacts:
    when: on_success
    name: "GenericNbiClient_${CI_COMMIT_TAG}"
    paths:
      - GenericNbiClient_${CI_COMMIT_TAG}/*
